# Generated by Django 4.0.5 on 2022-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebg',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='BG price'),
        ),
    ]
