# Generated by Django 4.0.5 on 2022-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_touridea'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='OfferGoods name')),
                ('price', models.IntegerField(verbose_name='OfferGoods price')),
                ('img', models.ImageField(upload_to='media', verbose_name='OfferGoods image')),
            ],
            options={
                'verbose_name': 'OfferGoods',
                'verbose_name_plural': 'OfferGoods',
            },
        ),
    ]
