# Generated by Django 4.0.5 on 2022-06-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_offergoods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='SwipeReserve name')),
                ('img', models.ImageField(upload_to='media', verbose_name='SwipeReserve image')),
                ('about', models.TextField(verbose_name='SwipeReserve')),
            ],
            options={
                'verbose_name': 'SwipeReserve',
                'verbose_name_plural': 'SwipeReserve',
            },
        ),
    ]
