# Generated by Django 4.0.5 on 2022-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_swipereserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Thinks name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Thinks image')),
                ('about', models.TextField(verbose_name='Thinks')),
                ('job', models.TextField(verbose_name='Job name')),
            ],
            options={
                'verbose_name': 'Thinks',
                'verbose_name_plural': 'Thinks',
            },
        ),
    ]
