# Generated by Django 4.0.5 on 2022-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_thinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextTourPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Place image')),
                ('name', models.CharField(max_length=30, verbose_name='Place name')),
                ('about', models.TextField(verbose_name='Place about')),
            ],
            options={
                'verbose_name': 'NextTourPlace',
                'verbose_name_plural': 'NextTourPlace',
            },
        ),
    ]
