# Generated by Django 4.0.5 on 2022-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_info1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media', verbose_name='info2 image1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Info2 image2')),
                ('text1', models.CharField(max_length=30, verbose_name='textinfo1')),
                ('text2', models.CharField(max_length=30, verbose_name='textinfo2')),
                ('about1', models.TextField(verbose_name='about1')),
                ('about2', models.TextField(verbose_name='about2')),
            ],
        ),
        migrations.AlterModelOptions(
            name='info1',
            options={'verbose_name': 'Info1', 'verbose_name_plural': 'Info1'},
        ),
    ]
